routes/web.php
                    ->header('Content-Disposition', "attachment; filename=$filename");
            });

        });
    });

    Route::group(['middlewareGroups' => ['web','settinguser','auth','verified','role:super_users']], function () {
        Route::middleware('permission:superusers')
        ->namespace('Admin')
        ->group(function (){
             Route::get('super-user-setting-up', 'UsersController@superuser');
        });   
     });

    Route::group(['middlewareGroups' => ['web','CekOpenedTransaction','BlockedBeforeSettingUser','verified','permission:developer|superusers']], function () {
        Route::middleware('permission:developer|superusers')
        ->namespace('Admin')
        ->group(function (){
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/edit-users/{id}/detail-data-users', 'UsersController@edit')->name('edit.master.users')->where('branch_id', '[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/update-users/{id}', 'UsersController@update')->name('users.updated')->where('branch_id', '[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/manage-users', 'UsersController@index')->name('users.list.index')->where('branch_id', '[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/create-users', 'UsersController@create')->name('users.create.index')->where('branch_id', '[0-9]+');
            Route::post('/dashboard/find-branch-with-branch/branch-id/{branch_id}/stored-users', 'UsersController@createUserNew')->name('users.new.super.index')->where('branch_id', '[0-9]+');
            Route::post('/dashboard/find-branch-with-branch/branch-id/{branch_id}/stored-super-users', 'UsersController@store')->name('users.new.super.users.index')->where('branch_id', '[0-9]+');
            // Only User unactive
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/user-unactive-list', 'UsersController@userUnactived')->name('users.trashed')->where('branch_id', '[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/user-unactive-list/{id}/user-restored', 'UsersController@restoreUsers')->name('users.restored.active')->where('branch_id','[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/restored-all-users', 'UsersController@restoreAllUser')->name('users.restote.all.active')->where('branch_id','[0-9]+');
        });
    });

    Route::group(['middlewareGroups' => ['web','BlockedBeforeSettingUser','verified','permission:developer|superusers|transport|warehouse|accounting']], function () {
        Route::middleware('permission:developer|superusers|transport|warehouse|accounting')
        ->namespace('Admin')
        ->group(function (){
            Route::resource('permissions', 'PermissionsController');
            Route::resource('roles', 'RolesController');
            Route::resource('users', 'UsersController');
            Route::post('permissions_mass_destroy', ['uses' => 'PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
            Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
            Route::get('updated-api-setting-branch/find/{company}/find-branch/{branch}', 'UsersController@updateSettingUserBranch');
            Route::get('company-loaded-super-user/find/{id}', 'UsersController@loadcompanies');
            Route::get('companies-automatics/search/{id}', [UsersController::class, 'searchbranchautomatic'])->name('searchbranch');
            Route::get('add-company-request', 'UsersController@add_companyenv__');
            Route::get('roles-fetch-all', 'UsersController@searchroles');
            Route::get('Async-super-user-roles/roles/{roles}/role/{role}/branch/{branch}', 'UsersController@SettingSyncRoles');
            Route::get('Async-super-company-all/roles/{companyroles}/find/{role}', 'UsersController@SyncRoleCompanies');
            Route::get('find-request-companies/find/{compid}', 'UsersController@findcompanyId');
            Route::get('find-request-deleted-roles/find/{id}', 'UsersController@SuperUserDeletedRole');
            Route::get('request-find-company-branchs/find/{indexid}', 'UsersController@loopdataBranch');
            Route::get('find-request-branchs/find/{brnchid}', 'UsersController@findbranchId');
            Route::get('find-request-roles/find/{roleId}', 'UsersController@findrolesId');
            Route::get('request-form-roles-users', 'UsersController@AddRolesAccessSuperusers');
            Route::get('add-branch-request', 'UsersController@add_branchenv__');
            Route::get('add-role-branch-request', 'UsersController@add_role_branch');
            Route::get('request-deleted-companies/find/{id}', 'UsersController@deletecompanies');
            Route::get('request-deleted-supers-users/find/{id}', 'UsersController@superusersdeleteusers');
            Route::get('companies/find/{id}', 'UsersController@loadbyfindcompanies');
            Route::get('roles-load', 'UsersController@load_with_roles');
            Route::get('registerUsers', 'UsersController@registerUsers');
            Route::get('get-users/find/{id}', 'UsersController@getUser');
            Route::get('company-branchs/find/{id}', 'UsersController@loadbyfindbranch');
            Route::get('company-branchs-fetch/find/{id}', 'UsersController@byfindbranchsftech');
            Route::get('create-object-company/find/{id}', 'UsersController@create_object_company');
            Route::get('company-brnch/find/{id}', 'UsersController@loadcompanybranch');
            Route::get('GetPersonalClient', 'UsersController@GetClientToken');
            Route::get('/loaded-company-branch', 'UsersController@loaded_company_branch');
            Route::get('/loaded-uuid-company-branch/find/{id}', 'UsersController@load_uuid_company_branch');
            Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
        });
    });

    Route::group(['middlewareGroups' => ['web','verified','permission:developer|superusers|transport|warehouse|accounting']], function () {
        Route::middleware('permission:developer|superusers|transport|warehouse|accounting')
        ->namespace('Admin')
        ->group(function (){
            Route::get('load-company-for-super-user', 'UsersController@loadCompanyReleatedSuperuser');
            Route::get('load-company-branch-with-super-user/find/{id}', 'UsersController@LoadBranchwithcompanysuperuser');
        });
    });

    Route::group(['middlewareGroups' => ['web','CekOpenedTransaction','BlockedBeforeSettingUser','verified']], function () {
        Route::middleware('permission:developer|superusers|warehouse|accounting|transport')
        ->namespace('Company')
        ->group(function (){
            Route::resource('Companys', 'CompaniesController');
        });
    });

    Route::group(['middlewareGroups' => ['web','CekOpenedTransaction','BlockedBeforeSettingUser','verified','role:administrator|super_users']], function () {
        Route::middleware('permission:developer|superusers|warehouse|accounting|transport')
        ->namespace('Branch')
        ->group(function (){
            Route::resource('Branchs', 'BranchController');
            Route::get('load-company', 'BranchController@loaded_company_branch');
        });
    });

    Route::group(['middlewareGroups' => ['web','BlockedBeforeSettingUser','verified','permission:developer|transport|accounting|superusers']], function () {
        Route::middleware('permission:developer|transport|accounting|superusers')
        ->namespace('history_order')
        ->group(function (){
            Route::get('/history-list', 'OrderHistoryController@index');
            Route::get('/history-find-it-details/{id}', 'OrderHistoryController@find_show_detail_status');
            Route::get('/history-find-it-details-tc/{id}', 'OrderHistoryController@find_show_detail_status_transports');
            Route::get('/history-find-it-details-jobs/{id}', 'OrderHistoryController@find_show_detail_status_Jobs');
            Route::resource('history_orders', 'OrderHistoryController');
        });
    });
    
    Route::group(['middlewareGroups' => ['web','CekOpenedTransaction','BlockedBeforeSettingUser','verified','role:3PL SURABAYA ALL PERMISSION|3PL - BANDUNG TRANSPORT|3PL - SURABAYA WAREHOUSE|super_users|administrator']], function () {
        Route::middleware('role:3PL - SURABAYA WAREHOUSE|3PL - BANDUNG TRANSPORT|super_users|administrator|3PL SURABAYA ALL PERMISSION|administrator')
        ->namespace('vehicle')
        ->group(function (){
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/detail-data-vehicle/{id}/update-data-vehicle', 'VehicleController@show')->name('update.master.vehicle')->where('branch_id', '[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/list-master-vehicle', 'VehicleController@index')->name('list.master.vehicle')->where('branch_id', '[0-9]+');
            Route::get('/dashboard/find-branch-with-branch/branch-id/{branch_id}/registration-vehicle', 'VehicleController@create')->name('registration.vehicle')->where('branch_id', '[0-9]+');
        });
    });

    Route::group(['middlewareGroups' => ['web','BlockedBeforeSettingUser','verified','role:super_users']], function () {
        Route::middleware('role:super_users')
        ->namespace('vehicle')
        ->group(function (){
            Route::resource('vehicle_accociate', 'VehicleController');
            Route::get('/vehicle-list-internal-list', 'VehicleController@internal_vehicle_loader');
            Route::get('/vehicle-list-internal-find/{id}', 'VehicleController@internal_vehicle_find_it');

app/Http/Controllers/Company/CompaniesController.php.php
<?php

namespace warehouse\Http\Controllers\Company;

use Illuminate\Http\Request;
use warehouse\Http\Controllers\Controller;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/Company/edit.blade.php
@extends('admin.layouts.master')
@section('head')
    <link rel="shortcut icon" href="../../img/logo.ico" />

    <link href="../../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="../../assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
    <link href="../../assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="../../css/style.css" rel="stylesheet" />
    <link href="../../css/style-responsive.css" rel="stylesheet" />
    <link href="../../css/style-default.css" rel="stylesheet" id="style_color" />

    <link href="../../assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="../../assets/uniform/css/uniform.default.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.5/dist/sweetalert2.min.css">

    <link rel="stylesheet" type="text/css" href="../../assets/chosen-bootstrap/chosen/chosen.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/select2.4.0.3/select2.min.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/jquery-tags-input/jquery.tagsinput.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/clockface/css/clockface.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/bootstrap-datepicker/css/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/bootstrap-timepicker/compiled/timepicker.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/bootstrap-colorpicker/css/colorpicker.css" />
    <link rel="stylesheet" href="../../assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/bootstrap-daterangepicker/daterangepicker.css" />

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

@endsection
@section('brand')
<a class="brand" href="/home">
    {{--  <img src="../img/logo.png" alt="Tiga Permata System" />  --}}
</a>
@endsection
@section('breadcrumb')
<li>
    <a href="/home"><i class="icon-home"></i></a>
    <span class="divider">/</span>
</li>
<li>
    <a href="{{ url('users') }}">Users List</a>
    <span class="divider">/</span>
</li>
<li class="active">
    {{ $menu}}
</li>
@endsection

@section('content')
<div id="main-content">
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
       <!-- BEGIN PAGE HEADER-->
       <div class="row-fluid">
          <div class="span12">
             <!-- BEGIN PAGE TITLE & BREADCRUMB-->
              <h3 class="page-title">
                   {{ $menu }}
              </h3>
              <ul class="breadcrumb">
                  @yield('breadcrumb')
              </ul>
              <!-- END PAGE TITLE & BREADCRUMB-->
          </div>
       </div>
       <!-- END PAGE HEADER-->

       <!-- BEGIN ADVANCED TABLE widget-->
       <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN EXAMPLE TABLE widget-->
                <div class="widget red">
                    <div class="widget-title">
                        <h4><i class="icon-reorder"></i> {{ $menu }}</h4>
                        <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                        </span>
                    </div>
                    <div class="widget-body">
                      @if ($errors->any())
                          <div class="alert alert-danger">
                              <strong>Whoops!</strong> There were some problems with your input.<br><br>
                              <ul>
                                  @foreach ($errors->all() as $error)
                                      <li>{{ $error }}</li>
                                  @endforeach
                              </ul>
                          </div>
                      @endif
                        <!-- BEGIN FORM-->
                        <form action="{{ route('Companys.update', $data_company->id) }}" class="form-horizontal" method="PUT">
                          <input type="hidden" name="_token" value="{{ csrf_token() }}" class="span12 " />
                        {{-- {{ method_field('PUT') }} --}}
                          <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label"><strong>Informasi Edit Company</strong></label>
                                    <div class="controls">
                                        {{--  <input type="text" class="span12 " />  --}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="control-group">
                                    <label class="control-label">Company</label>
                                    <div class="controls">
                                        <input type="text" maxlength="30" value="{{ $data_company->name }}" id="name" name="name" class="span12 " />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="row-fluid">
                                <div class="span12" style="text-align:right;" >
                                    <div class="form-actions" style=""   >
                                        <button type="submit" class="btn btn-success">Update</button>
                                        {{--  <button type="button" class="btn">Cancel</button>  --}}
                                        <a class="btn btn-warning" href="{{ route('Companys.index') }}">Cancel</a>
                                </div>
                            </div>
                        </div>
                      </form>
                    </div>
                </div>
            </div>
        </div>


        <!-- END ADVANCED TABLE widget-->

       <!-- END PAGE CONTENT-->
   </div>
</div>
@endsection

@section('javascript')

    <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
   @include('sweetalert::view')
   <script src="../../js/jquery-1.8.2.min.js"></script>
   <script src="../../js/jquery.nicescroll.js" type="text/javascript"></script>
   <script type="text/javascript" src="../../assets/ckeditor/ckeditor.js"></script>
   <script src="../../assets/bootstrap/js/bootstrap.min.js"></script>
   <script src="../../js/select2.min.js" type="text/javascript"></script>
   <script type="text/javascript" src="../../assets/bootstrap/js/bootstrap-fileupload.js"></script>
   <script src="../../js/jquery.blockui.js"></script>
   
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

   <script src="../../js/jQuery.dualListBox-1.3.js" language="javascript" type="text/javascript"></script>


   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->
   <script type="text/javascript" src="../../assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js"></script>
   <script type="text/javascript" src="../../assets/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
   <script type="text/javascript" src="../../assets/uniform/jquery.uniform.min.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
   <script type="text/javascript" src="../../assets/clockface/js/clockface.js"></script>
   <script type="text/javascript" src="../../assets/jquery-tags-input/jquery.tagsinput.min.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-daterangepicker/date.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-daterangepicker/daterangepicker.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
   <script type="text/javascript" src="../../assets/bootstrap-inputmask/bootstrap-inputmask.min.js"></script>
   <script src="../../assets/fancybox/source/jquery.fancybox.pack.js"></script>
   {{-- <script src="../../js/jquery.scrollTo.min.js"></script> --}}



   <!--common script for all pages-->
   <script src="../../js/common-scripts.js"></script>

   <!--script for this page-->
   <script src="../../js/form-component.js"></script>
  <!-- END JAVASCRIPTS -->

   <script language="javascript" type="text/javascript">
    
       $(function() {

           $.configureBoxes();

       });

    function show() {
    var p = document.getElementById('asd');
    p.setAttribute('type', 'text');
}

function hide() {
    var p = document.getElementById('asd');
    p.setAttribute('type', 'password');
}

var pwShown = 0;

document.getElementById("eye").addEventListener("click", function () {
    if (pwShown == 0) {
        pwShown = 1;
        show();
    } else {
        pwShown = 0;
        hide();
    }
}, false);
$(document).on('click', '.toggle-password', function() {

$(this).toggleClass("fa-eye fa-eye-slash");

    $('#asd').getAttribute('type') === 'password' ? $('#asd').getAttribute('type','text') : $('#asd').attr('type','password');
});

   </script>
@endsection

resources/views/admin/Company/index.blade.php
@extends('admin.layouts.master')
@section('head')
    <link rel="shortcut icon" href="../img/logo.ico" />
    <link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="../assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
    <link href="../assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="../css/style.css" rel="stylesheet" />
    <link href="../css/style-responsive.css" rel="stylesheet" />
    <link href="../css/style-default.css" rel="stylesheet" id="style_color" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="../assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="../assets/uniform/css/uniform.default.css" />
@endsection
@section('brand')
<a class="brand" href="/home">
</a>
@endsection
@section('breadcrumb')
<li>
    <a href="/home"><i class="icon-home"></i></a>
    <span class="divider">/</span>
</li>
<li>
    <a href="#">Users</a>
    <span class="divider">/</span>
</li>
<li class="active">
    {{ $menu }}
</li>
@endsection
@section('content')
<div id="main-content">
    <div class="container-fluid">
       <div class="row-fluid">
          <div class="span12">
              <h3 class="page-title">
                   {{ $menu }}
              </h3>
              <ul class="breadcrumb">
                  @yield('breadcrumb')
              </ul>
          </div>
       </div>
       @include('flash::message')
       @if (\Session::has('success'))
        <div class="alert alert-success">
          <p>{{ \Session::get('success') }}</p>
        </div>
        <br />
       @endif
       <div class="row-fluid">
            <div class="span12">
            <div class="widget red">
                <div class="widget-title">
                    <h4><i class="icon-reorder"></i> {{ $menu }}</h4>
                        <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                        </span>
                </div>
                <div class="widget-body">
                        <div style="text-align:left;">
                        </div>
                        <div style="text-align:right;">
                            <button type="button" class="btn btn-info" onclick="location.href='{{ route('Companys.create') }}'">
                                    <i class="icon-plus"></i>
                                        Add New
                            </button>
                        </div>
                    <div>
                        &nbsp;
                    </div>
                <table class="table table-striped table-bordered {{ count($data_company) > 0 ? 'datatable' : '' }} dt-select" id="sample_1">
                        <thead>
                            <tr>
                                <th>Company</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {{-- @if (count($users) > 0) --}}
                            @foreach ($data_company as $perusahaan)
                            <tr class="odd gradeX">
                                <td style="width: 90%;">{{ $perusahaan->name }}</td>
                                <td style="width: 16px;">
                                    <div class="span5">
                                      <button onclick="location.href='{{ URL::to('Companys/' . $perusahaan->id . '/edit')}}'" class="btn btn-xs btn-primary" type="button"><i class="fas fa-user-cog"></i></button>
                                    </div>
                                <form class="span6" action="{{route('Companys.destroy', $perusahaan->id)}}" method="post">
                                    {{ method_field('DELETE') }}
                                    <input type="hidden" name="_token" value="{{ @csrf_token()}}">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <div class="span5">
                                    <button type="submit" class="btn btn-xs btn-danger"><i class="fas fa-user-times"></i></button>
                                    </div>
                                </form>
                                </td>
                            </tr>
                            @endforeach()
                        {{-- @else
                            <tr>
                                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                            </tr> --}}
                        {{-- @endif --}}
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>
 </div>
@endsection
@section('javascript')
   <script src="../js/jquery-1.8.3.min.js"></script>
   <script src="../js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="../assets/bootstrap/js/bootstrap.min.js"></script>
   <script src="../js/jquery.blockui.js"></script>
   <script src="js/jquery.sparkline.js" type="text/javascript"></script>
   <script type="text/javascript" src="../assets/uniform/jquery.uniform.min.js"></script>
   <script type="text/javascript" src="../assets/data-tables/jquery.dataTables.js"></script>
   <script type="text/javascript" src="../assets/data-tables/DT_bootstrap.js"></script>
   <script src="../js/jquery.scrollTo.min.js"></script>
   <script src="../js/common-scripts.js"></script>
   <script src="../js/user-management-list.js"></script>
@endsection